CIRCUITPY_WIFI_SSID="__YOUR_WIFI_NETWORK_NAME__"
CIRCUITPY_WIFI_PASSWORD="__YOUR_WIFI_PASSWORD__"
CIRCUITPY_AIO_USERNAME="__ADAFRUIT_IO_USERNAME__"
CIRCUITPY_AIO_KEY="__YOUR_API_KEY_HERE__"
CIRCUITPY_WEB_API_PASSWORD="good-enough"
CIRCUITPY_WEB_INSTANCE_NAME="good enough Air Quality (CO2/VOC/PPM)"
GOOD_ENOUGH_MAX_LOG_ENTRIES=30
DISABLED_CIRCUITPY_PYSTACK_SIZE=1536
DISABLED_CIRCUITPY_RESERVED_PSRAM=